# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deriui.xml'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 782)
        MainWindow.setMinimumSize(QtCore.QSize(889, 515))
        MainWindow.setMaximumSize(QtCore.QSize(3333, 3333))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.placeHolderFrame = QtWidgets.QFrame(self.centralwidget)
        self.placeHolderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.placeHolderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.placeHolderFrame.setObjectName("placeHolderFrame")
        self.horizontalLayout_4.addWidget(self.placeHolderFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(328, 117))
        self.dockWidget_4.setMaximumSize(QtCore.QSize(328, 524287))
        self.dockWidget_4.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.orderbookTable = QtWidgets.QTableWidget(self.dockWidgetContents_4)
        self.orderbookTable.setEnabled(True)
        self.orderbookTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.orderbookTable.setAutoScroll(False)
        self.orderbookTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderbookTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.orderbookTable.setObjectName("orderbookTable")
        self.orderbookTable.setColumnCount(3)
        self.orderbookTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(2, item)
        self.orderbookTable.horizontalHeader().setVisible(True)
        self.orderbookTable.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.orderbookTable)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_4)
        self.dockWidget_5 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_5.setMinimumSize(QtCore.QSize(328, 236))
        self.dockWidget_5.setMaximumSize(QtCore.QSize(328, 236))
        self.dockWidget_5.setFloating(False)
        self.dockWidget_5.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.orderTabWidget = QtWidgets.QTabWidget(self.dockWidgetContents_5)
        self.orderTabWidget.setTabBarAutoHide(False)
        self.orderTabWidget.setObjectName("orderTabWidget")
        self.marketOrderTab = QtWidgets.QWidget()
        self.marketOrderTab.setObjectName("marketOrderTab")
        self.marketBuyButton = QtWidgets.QPushButton(self.marketOrderTab)
        self.marketBuyButton.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.marketBuyButton.setStyleSheet("background-color: green")
        self.marketBuyButton.setObjectName("marketBuyButton")
        self.marketSellButton = QtWidgets.QPushButton(self.marketOrderTab)
        self.marketSellButton.setGeometry(QtCore.QRect(210, 130, 81, 31))
        self.marketSellButton.setAutoFillBackground(False)
        self.marketSellButton.setStyleSheet("background-color: red")
        self.marketSellButton.setObjectName("marketSellButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.marketOrderTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 281, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.marketPriceInput = QtWidgets.QLineEdit(self.groupBox_4)
        self.marketPriceInput.setEnabled(False)
        self.marketPriceInput.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.marketPriceInput.setObjectName("marketPriceInput")
        self.groupBox = QtWidgets.QGroupBox(self.marketOrderTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 281, 61))
        self.groupBox.setObjectName("groupBox")
        self.marketOrderComboBox = QtWidgets.QComboBox(self.groupBox)
        self.marketOrderComboBox.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.marketOrderComboBox.setObjectName("marketOrderComboBox")
        self.marketOrderComboBox.addItem("")
        self.orderTabWidget.addTab(self.marketOrderTab, "")
        self.limitOrderTab = QtWidgets.QWidget()
        self.limitOrderTab.setObjectName("limitOrderTab")
        self.limitBuyButton = QtWidgets.QPushButton(self.limitOrderTab)
        self.limitBuyButton.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.limitBuyButton.setStyleSheet("background-color: green")
        self.limitBuyButton.setObjectName("limitBuyButton")
        self.limitSellButton = QtWidgets.QPushButton(self.limitOrderTab)
        self.limitSellButton.setGeometry(QtCore.QRect(210, 130, 81, 31))
        self.limitSellButton.setAutoFillBackground(False)
        self.limitSellButton.setStyleSheet("background-color: red")
        self.limitSellButton.setObjectName("limitSellButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.limitOrderTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 60, 281, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.limitPriceInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.limitPriceInput.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.limitPriceInput.setObjectName("limitPriceInput")
        self.groupBox_2 = QtWidgets.QGroupBox(self.limitOrderTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 281, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.limitOrderComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.limitOrderComboBox.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.limitOrderComboBox.setObjectName("limitOrderComboBox")
        self.limitOrderComboBox.addItem("")
        self.orderTabWidget.addTab(self.limitOrderTab, "")
        self.stopOrderTab = QtWidgets.QWidget()
        self.stopOrderTab.setObjectName("stopOrderTab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.stopOrderTab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 281, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.stopOrderComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.stopOrderComboBox.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.stopOrderComboBox.setObjectName("stopOrderComboBox")
        self.stopOrderComboBox.addItem("")
        self.stopMarketBuyButton = QtWidgets.QPushButton(self.stopOrderTab)
        self.stopMarketBuyButton.setGeometry(QtCore.QRect(10, 130, 81, 31))
        self.stopMarketBuyButton.setStyleSheet("background-color: green")
        self.stopMarketBuyButton.setObjectName("stopMarketBuyButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.stopOrderTab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 281, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.stopOrderPriceInput = QtWidgets.QLineEdit(self.groupBox_6)
        self.stopOrderPriceInput.setEnabled(True)
        self.stopOrderPriceInput.setGeometry(QtCore.QRect(10, 30, 261, 20))
        self.stopOrderPriceInput.setText("")
        self.stopOrderPriceInput.setObjectName("stopOrderPriceInput")
        self.stopMarketSellButton = QtWidgets.QPushButton(self.stopOrderTab)
        self.stopMarketSellButton.setGeometry(QtCore.QRect(210, 130, 81, 31))
        self.stopMarketSellButton.setAutoFillBackground(False)
        self.stopMarketSellButton.setStyleSheet("background-color: red")
        self.stopMarketSellButton.setObjectName("stopMarketSellButton")
        self.orderTabWidget.addTab(self.stopOrderTab, "")
        self.horizontalLayout_6.addWidget(self.orderTabWidget)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_5)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(220, 238))
        self.dockWidget_6.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dockWidgetContents_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents_6)
        self.tabWidget.setObjectName("tabWidget")
        self.currentPositionsTab = QtWidgets.QWidget()
        self.currentPositionsTab.setObjectName("currentPositionsTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.currentPositionsTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currentPositionsTable = QtWidgets.QTableWidget(self.currentPositionsTab)
        self.currentPositionsTable.setEnabled(True)
        self.currentPositionsTable.setAutoScroll(False)
        self.currentPositionsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.currentPositionsTable.setObjectName("currentPositionsTable")
        self.currentPositionsTable.setColumnCount(6)
        self.currentPositionsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(5, item)
        self.currentPositionsTable.horizontalHeader().setDefaultSectionSize(130)
        self.currentPositionsTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.currentPositionsTable)
        self.closePositionButton = QtWidgets.QPushButton(self.currentPositionsTab)
        self.closePositionButton.setMinimumSize(QtCore.QSize(100, 147))
        self.closePositionButton.setMaximumSize(QtCore.QSize(100, 147))
        self.closePositionButton.setAutoFillBackground(False)
        self.closePositionButton.setStyleSheet("")
        self.closePositionButton.setObjectName("closePositionButton")
        self.horizontalLayout_2.addWidget(self.closePositionButton)
        self.tabWidget.addTab(self.currentPositionsTab, "")
        self.openOrdersTab = QtWidgets.QWidget()
        self.openOrdersTab.setObjectName("openOrdersTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.openOrdersTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openOrderTable = QtWidgets.QTableWidget(self.openOrdersTab)
        self.openOrderTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.openOrderTable.setObjectName("openOrderTable")
        self.openOrderTable.setColumnCount(5)
        self.openOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(4, item)
        self.openOrderTable.horizontalHeader().setDefaultSectionSize(130)
        self.openOrderTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.openOrderTable)
        self.closeOrdersButton = QtWidgets.QPushButton(self.openOrdersTab)
        self.closeOrdersButton.setMinimumSize(QtCore.QSize(100, 147))
        self.closeOrdersButton.setMaximumSize(QtCore.QSize(100, 147))
        self.closeOrdersButton.setStyleSheet("")
        self.closeOrdersButton.setObjectName("closeOrdersButton")
        self.horizontalLayout_3.addWidget(self.closeOrdersButton)
        self.tabWidget.addTab(self.openOrdersTab, "")
        self.stopOrdersTab = QtWidgets.QWidget()
        self.stopOrdersTab.setObjectName("stopOrdersTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.stopOrdersTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stopOrderTable = QtWidgets.QTableWidget(self.stopOrdersTab)
        self.stopOrderTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stopOrderTable.setObjectName("stopOrderTable")
        self.stopOrderTable.setColumnCount(5)
        self.stopOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.stopOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stopOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stopOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stopOrderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stopOrderTable.setHorizontalHeaderItem(4, item)
        self.stopOrderTable.horizontalHeader().setCascadingSectionResizes(False)
        self.stopOrderTable.horizontalHeader().setDefaultSectionSize(130)
        self.stopOrderTable.horizontalHeader().setSortIndicatorShown(False)
        self.stopOrderTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_7.addWidget(self.stopOrderTable)
        self.closeStopOrdersButton = QtWidgets.QPushButton(self.stopOrdersTab)
        self.closeStopOrdersButton.setMinimumSize(QtCore.QSize(100, 147))
        self.closeStopOrdersButton.setMaximumSize(QtCore.QSize(100, 147))
        self.closeStopOrdersButton.setStyleSheet("")
        self.closeStopOrdersButton.setObjectName("closeStopOrdersButton")
        self.horizontalLayout_7.addWidget(self.closeStopOrdersButton)
        self.tabWidget.addTab(self.stopOrdersTab, "")
        self.accountInfoTab = QtWidgets.QWidget()
        self.accountInfoTab.setObjectName("accountInfoTab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.accountInfoTab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.accountInfoTable = QtWidgets.QTableWidget(self.accountInfoTab)
        self.accountInfoTable.setObjectName("accountInfoTable")
        self.accountInfoTable.setColumnCount(6)
        self.accountInfoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.accountInfoTable.setHorizontalHeaderItem(5, item)
        self.accountInfoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.accountInfoTable.horizontalHeader().setDefaultSectionSize(130)
        self.accountInfoTable.horizontalHeader().setSortIndicatorShown(False)
        self.accountInfoTable.horizontalHeader().setStretchLastSection(True)
        self.accountInfoTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_8.addWidget(self.accountInfoTable)
        self.tabWidget.addTab(self.accountInfoTab, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.dockWidget_6.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_6)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionWallets = QtWidgets.QAction(MainWindow)
        self.actionWallets.setObjectName("actionWallets")
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionWallets)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.orderTabWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deribit Trade Terminal"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "Orderbook"))
        item = self.orderbookTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price"))
        item = self.orderbookTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.orderbookTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        self.dockWidget_5.setWindowTitle(_translate("MainWindow", "Place Order"))
        self.marketBuyButton.setText(_translate("MainWindow", "Market Buy"))
        self.marketSellButton.setText(_translate("MainWindow", "Market Sell"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Price"))
        self.marketPriceInput.setText(_translate("MainWindow", "Market"))
        self.groupBox.setTitle(_translate("MainWindow", "Account Selection"))
        self.marketOrderComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.orderTabWidget.setTabText(self.orderTabWidget.indexOf(self.marketOrderTab), _translate("MainWindow", "MarketOrder"))
        self.limitBuyButton.setText(_translate("MainWindow", "Limit Buy"))
        self.limitSellButton.setText(_translate("MainWindow", "Limit Sell"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Price"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Account Selection"))
        self.limitOrderComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.orderTabWidget.setTabText(self.orderTabWidget.indexOf(self.limitOrderTab), _translate("MainWindow", "Limit Order"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Account Selection"))
        self.stopOrderComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.stopMarketBuyButton.setText(_translate("MainWindow", "Stop Buy"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Price"))
        self.stopMarketSellButton.setText(_translate("MainWindow", "Stop Sell"))
        self.orderTabWidget.setTabText(self.orderTabWidget.indexOf(self.stopOrderTab), _translate("MainWindow", "Stop Order"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "Additional Information"))
        item = self.currentPositionsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.currentPositionsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.currentPositionsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.currentPositionsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Avg Price"))
        item = self.currentPositionsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PNL"))
        item = self.currentPositionsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        self.closePositionButton.setText(_translate("MainWindow", "Close Positions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.currentPositionsTab), _translate("MainWindow", "Open Positions"))
        item = self.openOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.openOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.openOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.openOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.openOrderTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        self.closeOrdersButton.setText(_translate("MainWindow", "Close Orders"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.openOrdersTab), _translate("MainWindow", "Open Orders"))
        item = self.stopOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.stopOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.stopOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.stopOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.stopOrderTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        self.closeStopOrdersButton.setText(_translate("MainWindow", "Close Orders"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stopOrdersTab), _translate("MainWindow", "Stop Orders"))
        item = self.accountInfoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.accountInfoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Equity"))
        item = self.accountInfoTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Balance"))
        item = self.accountInfoTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Available"))
        item = self.accountInfoTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Initial Margin"))
        item = self.accountInfoTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Maintenance Margin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountInfoTab), _translate("MainWindow", "Account Info"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionWallets.setText(_translate("MainWindow", "Wallets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

