# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deriui.xml'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 515)
        MainWindow.setMinimumSize(QtCore.QSize(889, 515))
        MainWindow.setMaximumSize(QtCore.QSize(889, 515))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.orderTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.orderTabWidget.setGeometry(QtCore.QRect(10, 330, 561, 141))
        self.orderTabWidget.setTabBarAutoHide(False)
        self.orderTabWidget.setObjectName("orderTabWidget")
        self.marketOrderTab = QtWidgets.QWidget()
        self.marketOrderTab.setObjectName("marketOrderTab")
        self.marketBuyButton = QtWidgets.QPushButton(self.marketOrderTab)
        self.marketBuyButton.setGeometry(QtCore.QRect(0, 10, 121, 101))
        self.marketBuyButton.setStyleSheet("background-color: green")
        self.marketBuyButton.setObjectName("marketBuyButton")
        self.closePositionButton = QtWidgets.QPushButton(self.marketOrderTab)
        self.closePositionButton.setGeometry(QtCore.QRect(140, 10, 271, 101))
        self.closePositionButton.setAutoFillBackground(False)
        self.closePositionButton.setStyleSheet("background-color: yellow")
        self.closePositionButton.setObjectName("closePositionButton")
        self.marketSellButton = QtWidgets.QPushButton(self.marketOrderTab)
        self.marketSellButton.setGeometry(QtCore.QRect(430, 10, 121, 101))
        self.marketSellButton.setAutoFillBackground(False)
        self.marketSellButton.setStyleSheet("background-color: red")
        self.marketSellButton.setObjectName("marketSellButton")
        self.orderTabWidget.addTab(self.marketOrderTab, "")
        self.limitOrderTab = QtWidgets.QWidget()
        self.limitOrderTab.setObjectName("limitOrderTab")
        self.limitBuyButton = QtWidgets.QPushButton(self.limitOrderTab)
        self.limitBuyButton.setGeometry(QtCore.QRect(0, 10, 121, 101))
        self.limitBuyButton.setStyleSheet("background-color: green")
        self.limitBuyButton.setObjectName("limitBuyButton")
        self.closePositionButton2 = QtWidgets.QPushButton(self.limitOrderTab)
        self.closePositionButton2.setGeometry(QtCore.QRect(140, 70, 271, 41))
        self.closePositionButton2.setAutoFillBackground(False)
        self.closePositionButton2.setStyleSheet("background-color: yellow")
        self.closePositionButton2.setObjectName("closePositionButton2")
        self.limitSellButton = QtWidgets.QPushButton(self.limitOrderTab)
        self.limitSellButton.setGeometry(QtCore.QRect(430, 10, 121, 101))
        self.limitSellButton.setAutoFillBackground(False)
        self.limitSellButton.setStyleSheet("background-color: red")
        self.limitSellButton.setObjectName("limitSellButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.limitOrderTab)
        self.groupBox_3.setGeometry(QtCore.QRect(140, 10, 271, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.limitPriceInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.limitPriceInput.setGeometry(QtCore.QRect(20, 20, 231, 20))
        self.limitPriceInput.setObjectName("limitPriceInput")
        self.orderTabWidget.addTab(self.limitOrderTab, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 561, 161))
        self.groupBox.setObjectName("groupBox")
        self.currentPositionsTable = QtWidgets.QTableWidget(self.groupBox)
        self.currentPositionsTable.setEnabled(True)
        self.currentPositionsTable.setGeometry(QtCore.QRect(10, 20, 541, 131))
        self.currentPositionsTable.setAutoScroll(False)
        self.currentPositionsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.currentPositionsTable.setObjectName("currentPositionsTable")
        self.currentPositionsTable.setColumnCount(5)
        self.currentPositionsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.currentPositionsTable.setHorizontalHeaderItem(4, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 561, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.openOrderTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.openOrderTable.setGeometry(QtCore.QRect(10, 20, 411, 121))
        self.openOrderTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.openOrderTable.setObjectName("openOrderTable")
        self.openOrderTable.setColumnCount(4)
        self.openOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.openOrderTable.setHorizontalHeaderItem(3, item)
        self.closeOrdersButton = QtWidgets.QPushButton(self.groupBox_2)
        self.closeOrdersButton.setGeometry(QtCore.QRect(430, 20, 121, 121))
        self.closeOrdersButton.setStyleSheet("background-color: teal")
        self.closeOrdersButton.setObjectName("closeOrdersButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 10, 311, 461))
        self.groupBox_4.setObjectName("groupBox_4")
        self.orderbookTable = QtWidgets.QTableWidget(self.groupBox_4)
        self.orderbookTable.setEnabled(True)
        self.orderbookTable.setGeometry(QtCore.QRect(10, 20, 291, 431))
        self.orderbookTable.setAutoScroll(False)
        self.orderbookTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.orderbookTable.setObjectName("orderbookTable")
        self.orderbookTable.setColumnCount(3)
        self.orderbookTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderbookTable.setHorizontalHeaderItem(2, item)
        self.orderbookTable.horizontalHeader().setVisible(True)
        self.orderbookTable.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionWallets = QtWidgets.QAction(MainWindow)
        self.actionWallets.setObjectName("actionWallets")
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionWallets)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.orderTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deribit Trade Terminal"))
        self.marketBuyButton.setText(_translate("MainWindow", "Market Buy"))
        self.closePositionButton.setText(_translate("MainWindow", "Close Position"))
        self.marketSellButton.setText(_translate("MainWindow", "Market Sell"))
        self.orderTabWidget.setTabText(self.orderTabWidget.indexOf(self.marketOrderTab), _translate("MainWindow", "MarketOrder"))
        self.limitBuyButton.setText(_translate("MainWindow", "Limit Buy"))
        self.closePositionButton2.setText(_translate("MainWindow", "Close Positions"))
        self.limitSellButton.setText(_translate("MainWindow", "Limit Sell"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Price"))
        self.orderTabWidget.setTabText(self.orderTabWidget.indexOf(self.limitOrderTab), _translate("MainWindow", "Limit Order"))
        self.groupBox.setTitle(_translate("MainWindow", "Current Positions"))
        item = self.currentPositionsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.currentPositionsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.currentPositionsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.currentPositionsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Avg Price"))
        item = self.currentPositionsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PNL"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Open Orders"))
        item = self.openOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account"))
        item = self.openOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Direction"))
        item = self.openOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.openOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.closeOrdersButton.setText(_translate("MainWindow", "Close Orders"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Orderbook"))
        item = self.orderbookTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Price"))
        item = self.orderbookTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.orderbookTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Total"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionWallets.setText(_translate("MainWindow", "Wallets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

